// Scenario Data Engine

export const SCENARIO_DECK = [
  // --- PHASE 1: Garage Startup (Turns 1-10) ---
  { id: 'p1_1', phase: 1, advisor: "CTO: We need better servers or the prototype will crash during the demo.", text: "Your server is overheating. Do we buy AWS credits or use the free tier?", choiceA: { label: "Buy Premium AWS", effects: { money: -15, rep: +10, share: 0, team: +5 } }, choiceB: { label: "Free Tier Hack", effects: { money: +0, rep: -10, share: 0, team: -10 } } },
  { id: 'p1_2', phase: 1, advisor: "CFO: The Angel Investor wants 20% equity for $50k. It's steep.", text: "Angel Investor is offering a seed round.", choiceA: { label: "Accept Terms", effects: { money: +30, share: -20, rep: +5, team: 0 } }, choiceB: { label: "Decline, Bootstrap", effects: { money: -10, share: 0, rep: +10, team: -5 } } },
  { id: 'p1_3', phase: 1, advisor: "CMO: We could buy fake traffic to get our first 1,000 users.", text: "Early Marketing Strategy. Be honest or play dirty?", choiceA: { label: "Organic Growth", effects: { money: -5, rep: +10, share: 0, team: +5 } }, choiceB: { label: "Fake Traffic Bots", effects: { money: -15, rep: -20, share: 0, team: -5 } } },
  { id: 'p1_4', phase: 1, advisor: "Co-Founder: I've been doing 80% of the work. I want equal shares.", text: "A co-founder is demanding more equity.", choiceA: { label: "Give Equity", effects: { money: 0, share: -15, rep: 0, team: +15 } }, choiceB: { label: "Refuse Firmly", effects: { money: 0, share: +0, rep: -5, team: -20 } } },
  { id: 'p1_5', phase: 1, advisor: "Lead Dev: There's a major bug in the core feature. Do we delay the launch?", text: "Release date is tomorrow. Bug found.", choiceA: { label: "Delay for Polish", effects: { money: -10, rep: +15, share: 0, team: -5 } }, choiceB: { label: "Ship and Patch Later", effects: { money: +10, rep: -20, share: 0, team: -10 } } },
  { id: 'p1_6', phase: 1, advisor: "HR: Offering free lunches might boost our tiny team's morale.", text: "Team wants office perks.", choiceA: { label: "Order Food Catering", effects: { money: -15, rep: 0, share: 0, team: +15 } }, choiceB: { label: "Bring your own lunch", effects: { money: +5, rep: 0, share: 0, team: -10 } } },
  { id: 'p1_7', phase: 1, advisor: "CTO: The perfect .com domain name is for sale by a squatter.", text: "Premium Domain Name Negotiation.", choiceA: { label: "Buy the .com", effects: { money: -25, rep: +15, share: 0, team: +5 } }, choiceB: { label: "Stick with .io", effects: { money: 0, rep: -5, share: 0, team: 0 } } },
  { id: 'p1_8', phase: 1, advisor: "CMO: The intern posted a controversial meme on our official Twitter.", text: "Social media backlash.", choiceA: { label: "Fire Intern & Apologize", effects: { money: -5, rep: +10, share: 0, team: -15 } }, choiceB: { label: "Lean into the meme", effects: { money: +15, rep: -25, share: 0, team: +5 } } },
  { id: 'p1_9', phase: 1, advisor: "Lead Designer: My laptop is 5 years old. I can't export Figma files.", text: "Need new equipment.", choiceA: { label: "Buy a MacBook Pro", effects: { money: -15, rep: +0, share: 0, team: +20 } }, choiceB: { label: "Ignore the complaint", effects: { money: +0, rep: 0, share: 0, team: -25 } } },
  { id: 'p1_10', phase: 1, advisor: "CFO: A local competitor wants to acqui-hire us.", text: "Early Buyout Offer.", choiceA: { label: "Sell a huge stake", effects: { money: +40, rep: -10, share: -30, team: -10 } }, choiceB: { label: "Stay independent", effects: { money: -5, rep: +15, share: 0, team: +10 } } },

  // --- PHASE 2: Co-working Space (Turns 11-20) ---
  { id: 'p2_1', phase: 2, advisor: "HR: The core team is exhausted. We need team building.", text: "The developers have been crunching for 3 weeks.", choiceA: { label: "Send them to Hawaii", effects: { money: -20, rep: +5, share: 0, team: +25 } }, choiceB: { label: "Offer Stock Options", effects: { money: 0, rep: 0, share: -15, team: +15 } } },
  { id: 'p2_2', phase: 2, advisor: "CTO: A tech giant copied our UI. Should we sue?", text: "A massive competitor launched a clone of your app.", choiceA: { label: "Sue them (Costly)", effects: { money: -25, rep: +15, team: +10, share: 0 } }, choiceB: { label: "Pivot the Product", effects: { money: -10, rep: -5, team: -15, share: 0 } } },
  { id: 'p2_3', phase: 2, advisor: "COO: We are outgrowing the co-working space. Need an actual office.", text: "Office Expansion.", choiceA: { label: "Rent a fancy space", effects: { money: -30, rep: +15, share: 0, team: +20 } }, choiceB: { label: "Cram into smaller space", effects: { money: +10, rep: -10, share: 0, team: -20 } } },
  { id: 'p2_4', phase: 2, advisor: "CMO: Do we pour the budget into dev speed or ad campaigns?", text: "Budget allocation.", choiceA: { label: "Huge Ad Campaign", effects: { money: -25, rep: +25, share: 0, team: -10 } }, choiceB: { label: "Hire 3 Senior Devs", effects: { money: -25, rep: -5, share: 0, team: +30 } } },
  { id: 'p2_5', phase: 2, advisor: "CFO: A sketchy vendor offers a 50% discount on cloud hosting.", text: "Shady business deals.", choiceA: { label: "Sign the contract", effects: { money: +25, rep: -20, share: 0, team: -5 } }, choiceB: { label: "Stay with reliable hosting", effects: { money: -15, rep: +10, share: 0, team: +10 } } },
  { id: 'p2_6', phase: 2, advisor: "HR: Our top engineer is brilliant but toxic. They made a junior cry.", text: "Toxic Top Performer.", choiceA: { label: "Fire the genius", effects: { money: -15, rep: +5, share: 0, team: +25 } }, choiceB: { label: "Protect them for output", effects: { money: +20, rep: -15, share: 0, team: -25 } } },
  { id: 'p2_7', phase: 2, advisor: "Head of Sales: A big enterprise wants to partner, but demands custom features.", text: "Enterprise B2B Deal.", choiceA: { label: "Accept B2B Deal", effects: { money: +35, rep: +5, share: 0, team: -20 } }, choiceB: { label: "Focus on B2C", effects: { money: -15, rep: +15, share: 0, team: +10 } } },
  { id: 'p2_8', phase: 2, advisor: "CTO: A FAANG company is trying to poach our lead developer.", text: "Poaching Attempt.", choiceA: { label: "Match the insane salary", effects: { money: -25, rep: 0, share: 0, team: +15 } }, choiceB: { label: "Let them go", effects: { money: +10, rep: -10, share: 0, team: -25 } } },
  { id: 'p2_9', phase: 2, advisor: "Board: Stop burning money. Sacrifice culture for growth metrics.", text: "Investor Pressure.", choiceA: { label: "Obey investors", effects: { money: +25, rep: -10, share: -5, team: -20 } }, choiceB: { label: "Defy them", effects: { money: -20, rep: +15, share: +10, team: +15 } } },
  { id: 'p2_10', phase: 2, advisor: "PR: Forbes wants an interview. Do we hype the product or stay humble?", text: "Forbes 30 Under 30 Interview.", choiceA: { label: "Over-hype the vision", effects: { money: +15, rep: +20, share: 0, team: -10 } }, choiceB: { label: "Be realistic & humble", effects: { money: -5, rep: -5, share: 0, team: +15 } } },

  // --- PHASE 3: Private Office (Turns 21-30) ---
  { id: 'p3_1', phase: 3, advisor: "CFO: A VC cartel offers Series A, but demands board seats.", text: "Mega VC Series A Investment.", choiceA: { label: "Take the Money", effects: { money: +40, share: -30, rep: +20, team: 0 } }, choiceB: { label: "Seek Crowdfunding", effects: { money: +15, share: -5, rep: +15, team: -10 } } },
  { id: 'p3_2', phase: 3, advisor: "PR: A popular influencer trashed our product online.", text: "PR Crisis Incident.", choiceA: { label: "Bribe Influnecer", effects: { money: -20, rep: -15, share: 0, team: -5 } }, choiceB: { label: "Public Apology", effects: { money: 0, rep: +15, share: 0, team: +5 } } },
  { id: 'p3_3', phase: 3, advisor: "HR: Employees are secretly discussing unionization.", text: "Unionization Threat.", choiceA: { label: "Crush the union", effects: { money: +15, rep: -25, share: 0, team: -30 } }, choiceB: { label: "Work with them", effects: { money: -30, rep: +20, share: 0, team: +25 } } },
  { id: 'p3_4', phase: 3, advisor: "CTO: We've been breached. Customer passwords might be stolen.", text: "Cybersecurity Breach.", choiceA: { label: "Cover it up", effects: { money: +10, rep: -40, share: 0, team: -10 } }, choiceB: { label: "Disclose & compensate", effects: { money: -35, rep: +15, share: 0, team: +10 } } },
  { id: 'p3_5', phase: 3, advisor: "COO: Time to expand to the European market?", text: "International Expansion.", choiceA: { label: "Aggressive EU Push", effects: { money: -30, rep: +25, share: 0, team: -15 } }, choiceB: { label: "Focus Local", effects: { money: +15, rep: -10, share: 0, team: +15 } } },
  { id: 'p3_6', phase: 3, advisor: "CTO: Should we open-source some of our core networking code?", text: "Open Source Strategy.", choiceA: { label: "Yes, release it", effects: { money: -15, rep: +30, share: 0, team: +15 } }, choiceB: { label: "Keep it proprietary", effects: { money: +15, rep: -15, share: 0, team: -5 } } },
  { id: 'p3_7', phase: 3, advisor: "Legal: A board member is trying to block a crucial vote.", text: "Boardroom Brawl.", choiceA: { label: "Buy out their shares", effects: { money: -40, rep: 0, share: +25, team: 0 } }, choiceB: { label: "Yield to their demands", effects: { money: +10, rep: -5, share: -15, team: -10 } } },
  { id: 'p3_8', phase: 3, advisor: "Lead Dev: Our codebase is a mess. We need to rewrite everything.", text: "Technical Debt.", choiceA: { label: "Greenlight rewrite", effects: { money: -25, rep: -10, share: 0, team: +20 } }, choiceB: { label: "Keep patching it", effects: { money: +15, rep: -20, share: 0, team: -20 } } },
  { id: 'p3_9', phase: 3, advisor: "CMO: A controversial sports team wants us as their main sponsor.", text: "Sponsorship Deal.", choiceA: { label: "Take the deal", effects: { money: -20, rep: +25, share: 0, team: -15 } }, choiceB: { label: "Decline it", effects: { money: +5, rep: -5, share: 0, team: +10 } } },
  { id: 'p3_10', phase: 3, advisor: "CTO: AWS went down and took us with it. Users are furious.", text: "Cloud Provider Outage.", choiceA: { label: "Blame AWS publicly", effects: { money: 0, rep: +5, share: 0, team: -10 } }, choiceB: { label: "Offer refunds", effects: { money: -25, rep: +20, share: 0, team: +10 } } },

  // --- PHASE 4: Corporate HQ (Turns 31-40) ---
  { id: 'p4_1', phase: 4, advisor: "Head of AI: We can sell user data to boost Q3 earnings.", text: "Lucrative Data Monetization Contract.", choiceA: { label: "Sell Data (Profit)", effects: { money: +40, rep: -30, team: -10, share: 0 } }, choiceB: { label: "Protect Privacy", effects: { money: -10, rep: +25, team: +10, share: 0 } } },
  { id: 'p4_2', phase: 4, advisor: "CFO: Our biggest rival is going bankrupt. We can buy them for pennies.", text: "Acquisition Opportunity.", choiceA: { label: "Acquire & absorb", effects: { money: -35, rep: +20, share: 0, team: -15 } }, choiceB: { label: "Let them die", effects: { money: +10, rep: -5, share: 0, team: +10 } } },
  { id: 'p4_3', phase: 4, advisor: "Legal: New regulations might kill our business model. Should we lobby?", text: "Government Regulation Threat.", choiceA: { label: "Spend millions lobbying", effects: { money: -30, rep: -15, share: 0, team: +10 } }, choiceB: { label: "Adapt the product", effects: { money: -15, rep: +25, share: 0, team: -20 } } },
  { id: 'p4_4', phase: 4, advisor: "PR: Our COO was caught in a massive scandal. Press is at our doors.", text: "Executive Scandal.", choiceA: { label: "Fire COO immediately", effects: { money: -15, rep: +20, share: +10, team: -15 } }, choiceB: { label: "Protect the COO", effects: { money: +10, rep: -35, share: 0, team: -5 } } },
  { id: 'p4_5', phase: 4, advisor: "HR: Growth is exploding. We should hire 500 people this quarter.", text: "Mass Hiring Wave.", choiceA: { label: "Hyper-growth hiring", effects: { money: -35, rep: +15, share: 0, team: -20 } }, choiceB: { label: "Keep team lean", effects: { money: +20, rep: -10, share: 0, team: +15 } } },
  { id: 'p4_6', phase: 4, advisor: "PR: Pledging to be carbon neutral will cost us 10% of revenue.", text: "Going Green Initiative.", choiceA: { label: "Pledge Carbon Neutral", effects: { money: -25, rep: +35, share: 0, team: +15 } }, choiceB: { label: "Ignore the climate", effects: { money: +20, rep: -20, share: 0, team: -10 } } },
  { id: 'p4_7', phase: 4, advisor: "Legal: Regulators are opening an antitrust monopoly investigation.", text: "Monopoly Probe.", choiceA: { label: "Cooperate fully", effects: { money: -20, rep: +20, share: 0, team: -5 } }, choiceB: { label: "Fight in court", effects: { money: -30, rep: -15, share: 0, team: +10 } } },
  { id: 'p4_8', phase: 4, advisor: "CTO: The core product is stalling. Let's pivot to hardware.", text: "Hardware Product Pivot.", choiceA: { label: "Launch Hardware", effects: { money: -40, rep: +25, share: 0, team: -10 } }, choiceB: { label: "Stick to Software", effects: { money: +15, rep: -5, share: 0, team: +10 } } },
  { id: 'p4_9', phase: 4, advisor: "CMO: We secured a slot for a Super Bowl halftime commercial.", text: "Super Bowl Ad.", choiceA: { label: "Spend $10M on Ad", effects: { money: -35, rep: +35, share: 0, team: +5 } }, choiceB: { label: "Save the money", effects: { money: +15, rep: -10, share: 0, team: -5 } } },
  { id: 'p4_10', phase: 4, advisor: "Board: A conglomerate initiated a hostile takeover bid.", text: "Hostile Takeover.", choiceA: { label: "Deploy 'Poison Pill'", effects: { money: -20, rep: -10, share: +30, team: 0 } }, choiceB: { label: "Negotiate surrender", effects: { money: +40, rep: -5, share: -45, team: -20 } } },

  // --- PHASE 5: Global Enterprise (Turns 41-50) ---
  { id: 'p5_1', phase: 5, advisor: "CFO: Wall Street wants us to lay off 10% of staff before IPO.", text: "Pre-IPO Corporate Restructuring.", choiceA: { label: "Execute Layoffs", effects: { money: +25, share: +10, team: -40, rep: -15 } }, choiceB: { label: "Protect Employees", effects: { money: -25, share: -15, team: +30, rep: +20 } } },
  { id: 'p5_2', phase: 5, advisor: "CFO: A sudden global recession is destroying the markets.", text: "Global Economic Crash.", choiceA: { label: "Liquidate assets", effects: { money: +35, rep: -20, share: -10, team: -20 } }, choiceB: { label: "Hold and suffer", effects: { money: -40, rep: +15, share: 0, team: +15 } } },
  { id: 'p5_3', phase: 5, advisor: "CTO: Replacing middle management with our AI will save billions.", text: "Next-Gen AI Integration.", choiceA: { label: "Automate Managers", effects: { money: +35, rep: -30, share: 0, team: -35 } }, choiceB: { label: "Keep human elements", effects: { money: -20, rep: +25, share: 0, team: +25 } } },
  { id: 'p5_4', phase: 5, advisor: "Legal: Our ultra-billionaire rival wants to settle all patent wars.", text: "Billionaire Truce.", choiceA: { label: "Sign historic truce", effects: { money: +20, rep: +15, share: 0, team: -5 } }, choiceB: { label: "Crush them entirely", effects: { money: -35, rep: -5, share: +25, team: +15 } } },
  { id: 'p5_5', phase: 5, advisor: "PR: A highly controversial political candidate wants our endorsement.", text: "Political Endorsement Request.", choiceA: { label: "Endorse for favors", effects: { money: +35, rep: -40, share: 0, team: -15 } }, choiceB: { label: "Remain strictly neutral", effects: { money: -15, rep: +20, share: 0, team: +5 } } },
  { id: 'p5_6', phase: 5, advisor: "Board: We have surplus capital. Should we test Universal Basic Income?", text: "UBI Social Experiment.", choiceA: { label: "Fund the UBI town", effects: { money: -45, rep: +45, share: 0, team: +10 } }, choiceB: { label: "Issue a huge dividend", effects: { money: +10, rep: -15, share: -15, team: -10 } } },
  { id: 'p5_7', phase: 5, advisor: "CTO: The next frontier is commercial space flight. Do we invest?", text: "Space Tech Investment.", choiceA: { label: "Fund asteroid mining", effects: { money: -45, rep: +30, share: +15, team: -10 } }, choiceB: { label: "Stay on Earth", effects: { money: +20, rep: -10, share: 0, team: +5 } } },
  { id: 'p5_8', phase: 5, advisor: "CFO: A massive stock buyback will cement your complete control.", text: "Massive Stock Buyback.", choiceA: { label: "Buy back everything", effects: { money: -45, rep: -10, share: +40, team: 0 } }, choiceB: { label: "Distribute bonuses", effects: { money: -25, rep: +20, share: -5, team: +30 } } },
  { id: 'p5_9', phase: 5, advisor: "COO: The Board wants to rebrand the entire company into the 'Omniverse'.", text: "Metaverse Transition.", choiceA: { label: "Embrace the Omniverse", effects: { money: -30, rep: -20, share: +10, team: -15 } }, choiceB: { label: "Reject the buzzword", effects: { money: +15, rep: +25, share: 0, team: +15 } } },
  { id: 'p5_10', phase: 5, advisor: "Lead Underwriter: It's the final IPO day. Do we price shares aggressively?", text: "Final IPO Pricing Strategy.", choiceA: { label: "Max Price (Greed)", effects: { money: +45, rep: -25, share: -25, team: -10 } }, choiceB: { label: "Fair Price (Legacy)", effects: { money: -20, rep: +35, share: -15, team: +15 } } }
];

export const getScenarioForPhase = (phase, excludeIds = []) => {
  let pool = SCENARIO_DECK.filter(s => s.phase === phase && !excludeIds.includes(s.id));
  
  if (pool.length === 0) {
    pool = SCENARIO_DECK.filter(s => s.phase === phase); // Repeat pool if all unique are exhausted
  }
  if (pool.length === 0) {
    pool = SCENARIO_DECK; 
  }

  const randomIndex = Math.floor(Math.random() * pool.length);
  return pool[randomIndex];
};
